matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
    - os: linux
      sudo: required
      dist: trusty
      language: node_js
      node_js: "10"
script:
  - npm test
